#!/usr/bin/env php

<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$shell = new Application();

// Command register
$shell->add(new \ActivismeBe\Artillery\Commands\ControllerCommand());
// END Command register

$shell->run();
