#!/usr/bin/env php
<?php

use ActivismeBe\Artillery\Commands\ControllerCommand;
use ActivismeBe\Artillery\Commands\CreateLibraryCommand;
use ActivismeBe\Artillery\Commands\ModelCodeigniterCommand;
use ActivismeBe\Artillery\Commands\ModelEloquentCommand;
use Symfony\Component\Console\Application;

// Debugging code
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
//> End debugging code


require __DIR__ . '/vendor/autoload.php';

$shell = new \Symfony\Component\Console\Application('Artillery', 'v1.0.0-dev');

$shell->add(new \ActivismeBe\Artillery\Commands\ControllerCommand());
$shell->add(new \ActivismeBe\Artillery\Commands\ModelCodeigniterCommand());
$shell->add(new \ActivismeBe\Artillery\Commands\ModelEloquentCommand());
$shell->add(new \ActivismeBe\Artillery\Commands\CreateLibraryCommand());
$shell->add(new \ActivismeBe\Artillery\Commands\CreateAuthCommand());
// $shell->add(new \ActivismeBe\Artillery\Commands\CreateMiddlewareCommand());
// $shell->add(new \ActivismeBe\Artillery\Commands\CreateHelperCommand());
$shell->add(new CreateLibraryCommand());
// $shell->add(new \ActivismeBe\Artillery\Commands\CreateLicenseCommand());
// $shell->add(new \ActivismeBe\Artillery\Commands\CreateLanguageFileCommand());

$shell->run();
